### PR TITLE
Only install ember-cli-shims if it doesn't exist

### LINKED ISSUE #254: 2.0.0 still trying to bower install packages on Ember 2.11.0
## Version
2.0.0

## Test Case
N/A

## Steps to reproduce
* A repo that's been upgraded to `ember-cli@2.11.0` (and hence has no core Ember packages in `bower.json`)
* However, this repo still has a `bower.json` for some third-party libraries that still need Bower (waiting on these libraries to have 2.11.0 support)
* `% ember install ember-composable-helpers`

## Expected Behavior
Nothing gets added to `bower.json`

## Actual Behavior
`ember-cli-shims` is installed via Bower.

This is the output from `ember install ember-composable-helpers`:

    % ember install ember-composable-helpers
    installing ember-composable-helpers
    install bower package ember-cli-shims
    cached https://github.com/ember-cli/ember-cli-shims.git#0.1.3
    cached https://github.com/components/ember.git#2.11.0
    Installed browser packages via Bower.
    Installed addon package.

*However*, if I remove/rename my `bower.json` first, then I get:

    % ember install ember-composable-helpers
    installing ember-composable-helpers
    install bower package ember-cli-shims
    WARNING: Skipping bower install: bower.json not found
    Installed addon package.

### PR DESCRIPTION
**Pull request by jrjohnson**
## Changes proposed in this pull request

Check first to see if ember-cli-shims is installed as a package (which
it is after ember-cli 2.11.

Closes #254 

Some caveats:
1) This is the only idea I had for preventing an unnecessary bower install. It might be a bad one.
2) I don't have any knowledge of the `options` parameter I used to detect the installation of `ember-cli-shims` - passing it in is part of the API docs at https://ember-cli.com/api/classes/Blueprint.html but there are no details.
3) I don't think there is a way to test the blueprint.

### CODE REVIEW

File: blueprints/ember-composable-helpers/index.js [hunk 1]
```diff
@@ -1,7 +1,9 @@
 module.exports = {
   normalizeEntityName: function() {},
 
-  afterInstall: function() {
-    return this.addBowerPackageToProject('ember-cli-shims', '~0.1.1');
+  afterInstall: function(options) {
+    if (!('ember-cli-shims' in options.project.addonPackages)) {
```
Comment (rtablada) [inline blueprints/ember-composable-helpers/index.js]: Maybe change this to using `indexOf` to support legacy node?

Comment (jrjohnson) [inline blueprints/ember-composable-helpers/index.js]: `addonPackages` is an object with each package as a key and I think the `in` operator for a key of an object works all the way back to ES3. I'm willing to be wrong about that though - just let me know.

**Comment by rtablada** [comment]
Forgot it was an object. You're right! LGTM!

-- 
Ryan Tablada
